<footer>
    <div class="copyright">
        <div class="container">
            <p><a class="copyright-link">
                    Chartered-flight... »&nbsp;2001-
                    <script type="text/javascript">
                        var d = new Date();
                        document.write(d.getFullYear());
                    </script>
                </a></p>
        </div>
    </div>
</footer>
